// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2temperature.proto

package service2temperature;

public interface AirConRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string coolingAC = 1;</code>
   */
  java.lang.String getCoolingAC();
  /**
   * <code>string coolingAC = 1;</code>
   */
  com.google.protobuf.ByteString
      getCoolingACBytes();
}
