// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2temperature.proto

package service2temperature;

public interface AirConResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AirConResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string warmingAC = 1;</code>
   */
  java.lang.String getWarmingAC();
  /**
   * <code>string warmingAC = 1;</code>
   */
  com.google.protobuf.ByteString
      getWarmingACBytes();
}
