// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2temperature.proto

package service2temperature;

public interface HeatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tooCold = 1;</code>
   */
  java.lang.String getTooCold();
  /**
   * <code>string tooCold = 1;</code>
   */
  com.google.protobuf.ByteString
      getTooColdBytes();
}
