// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2temperature.proto

package service2temperature;

public interface HeatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tooHot = 1;</code>
   */
  java.lang.String getTooHot();
  /**
   * <code>string tooHot = 1;</code>
   */
  com.google.protobuf.ByteString
      getTooHotBytes();
}
