// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2temperature.proto

package service2temperature;

public final class TemperatureControlImpl {
  private TemperatureControlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AirConResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AirConResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WindowsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WindowsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WindowsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WindowsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031service2temperature.proto\" \n\016HeatingRe" +
      "quest\022\016\n\006tooHot\030\001 \001(\t\"\"\n\017HeatingResponse" +
      "\022\017\n\007tooCold\030\001 \001(\t\"\"\n\rAirConRequest\022\021\n\tco" +
      "olingAC\030\001 \001(\t\"#\n\016AirConResponse\022\021\n\twarmi" +
      "ngAC\030\001 \001(\t\"$\n\016WindowsRequest\022\022\n\nopenWind" +
      "ow\030\001 \001(\t\"&\n\017WindowsResponse\022\023\n\013closeWind" +
      "ow\030\001 \001(\t2\263\001\n\010Service2\0227\n\016HeatingControl\022" +
      "\017.HeatingRequest\032\020.HeatingResponse\"\0000\001\0224" +
      "\n\rAirConControl\022\016.AirConRequest\032\017.AirCon" +
      "Response\"\000(\001\0228\n\rWindowControl\022\017.WindowsR" +
      "equest\032\020.WindowsResponse\"\000(\0010\001B/\n\023servic" +
      "e2temperatureB\026TemperatureControlImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_HeatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingRequest_descriptor,
        new java.lang.String[] { "TooHot", });
    internal_static_HeatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeatingResponse_descriptor,
        new java.lang.String[] { "TooCold", });
    internal_static_AirConRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AirConRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConRequest_descriptor,
        new java.lang.String[] { "CoolingAC", });
    internal_static_AirConResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_AirConResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AirConResponse_descriptor,
        new java.lang.String[] { "WarmingAC", });
    internal_static_WindowsRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_WindowsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WindowsRequest_descriptor,
        new java.lang.String[] { "OpenWindow", });
    internal_static_WindowsResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_WindowsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WindowsResponse_descriptor,
        new java.lang.String[] { "CloseWindow", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
