// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2temperature.proto

package service2temperature;

public interface WindowsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WindowsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string closeWindow = 1;</code>
   */
  java.lang.String getCloseWindow();
  /**
   * <code>string closeWindow = 1;</code>
   */
  com.google.protobuf.ByteString
      getCloseWindowBytes();
}
