// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2temperature.proto

package service2temperature;

public interface WindowsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WindowsRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string openWindow = 1;</code>
   */
  java.lang.String getOpenWindow();
  /**
   * <code>string openWindow = 1;</code>
   */
  com.google.protobuf.ByteString
      getOpenWindowBytes();
}
