// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1security.proto

package service1security;

public interface CodeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CodeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string enterCode = 1;</code>
   */
  java.lang.String getEnterCode();
  /**
   * <code>string enterCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getEnterCodeBytes();
}
