// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1security.proto

package service1security;

public interface CodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string checkCode = 1;</code>
   */
  java.lang.String getCheckCode();
  /**
   * <code>string checkCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getCheckCodeBytes();
}
